# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce576cb87b69d9caafee26fbded56d32aa9be7f8714ec1435370c47cc44eb5d0cda4bbbeecb2a3eb6e7118261eb921fdc9b559e256e63e167e1b2bcc21a041b4

test:
  secret_key_base: 010d43ebe8f0e56cf85416d9cb000b9de9217255a62b33e0f7e79f26ec5418283927096a32b76ac800c25fb4e09c79d431afe9088eae2d25b298b0ffecdd122a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
